# Generated by Django 4.2.16 on 2024-11-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
