# Generated by Django 4.2.16 on 2024-11-22 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
