# Generated by Django 4.2.16 on 2024-11-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_log_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
