services:
  db:
    container_name: db
    image: postgres:15-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    env_file:
        - ./loghub/.env
        



  web:
    container_name: web
    image: web
    build: 
       context: .
       dockerfile: ./docker/django/Dockerfile
    command: /start.sh
    restart: always
    volumes:
      - ./loghub:/app
      - static_volume:/app/static
      - media_volume:/app/media

    ports:
      - "8000:8000"

    env_file:
        - path: ./loghub/.env

    depends_on:
      - db 
    
volumes:
  static_volume:
  media_volume:
  postgres_data: