# Generated by Django 5.1.3 on 2024-11-19 12:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/categories')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Please use only alphabetic English characters.', regex='^[a-zA-Z]+$')])),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('is_root', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='category.categorydetail')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
                ('category_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='category.categorydetail')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ids', models.JSONField()),
                ('included_childs', models.JSONField()),
                ('excluded_childs', models.JSONField()),
                ('keyword', models.SlugField(blank=True, null=True, unique=True)),
                ('permission_type', models.CharField(choices=[('None', 'None'), ('Anyone', 'Anyone'), ('User', 'User'), ('Keyword', 'Keyword'), ('Mix', 'Mix')], default='None', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access_categories', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('category_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='category.categorydetail')),
            ],
        ),
    ]
