# Generated by Django 5.1.3 on 2024-12-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_description_alter_category_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorypermission",
            name="keyword",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
