# Generated by Django 5.1.3 on 2024-12-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_categorypermission_keyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorypermission",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="User_access_category",
                to="category.category",
            ),
        ),
    ]
